SET NAMES utf8mb4;

INSERT INTO challenges (id, title, description, difficulty, points, category, media_type) VALUES
('c16', 'Sentarte en la mesa mas grande solo', 'En un restaurante o food court, sentate en una mesa para 6+ personas estando solo', 'facil', 5, 'social', 'foto'),
('c17', 'Pedir agua gratis', 'En un bar o restaurante, pedi solo un vaso de agua sin consumir nada mas', 'facil', 5, 'social', 'video'),
('c18', 'Usar el ascensor para un piso', 'Subi o baja un solo piso en ascensor con gente mirandote', 'facil', 5, 'cotidiano', 'video'),
('c19', 'Preguntar la hora a alguien con reloj', 'Preguntale la hora a alguien que claramente tiene reloj o celular en la mano', 'facil', 5, 'social', 'video'),
('c20', 'Pedir servilletas extra', 'En cualquier local de comida, pedi un monton de servilletas extra sin razon aparente', 'facil', 5, 'social', 'video'),
('c21', 'Foto con un desconocido', 'Pedile a un desconocido que se saque una foto con vos', 'facil', 5, 'social', 'foto'),
('c22', 'Dejar propina en monedas', 'Deja propina pero toda en monedas, contandolas una por una', 'facil', 5, 'social', 'foto'),
('c23', 'Sentarte en el piso en un lugar publico', 'Sentate en el piso de un shopping, estacion o lugar publico por al menos 30 segundos', 'facil', 5, 'cotidiano', 'foto'),
('c24', 'Regatear en un kiosco', 'Intenta regatear el precio de algo en un kiosco o almacen', 'medio', 8, 'social', 'video'),
('c25', 'Pedir probar un perfume', 'En una perfumeria, pedi probar 3 perfumes y andate sin comprar', 'medio', 8, 'social', 'video'),
('c26', 'Hablar en voz alta por telefono', 'Mantene una conversacion en voz alta (real o falsa) en un lugar publico por 30 segundos', 'medio', 8, 'performance', 'video'),
('c27', 'Pedir cambio sin comprar', 'Entra a un local y pedi cambio de un billete sin comprar nada', 'medio', 8, 'social', 'video'),
('c28', 'Preguntar si aceptan trueque', 'En cualquier comercio, pregunta si podes pagar con un trueque', 'medio', 8, 'social', 'video'),
('c29', 'Pedir el banio en un local sin consumir', 'Entra a un bar o restaurante y pedi usar el banio sin ser cliente', 'medio', 8, 'social', 'video'),
('c30', 'Saludar a todos en un ascensor', 'Al entrar a un ascensor con gente, saluda a cada persona individualmente', 'medio', 8, 'social', 'video'),
('c31', 'Devolver algo sin ticket', 'Intenta devolver algo en un local sin tener el ticket de compra', 'medio', 8, 'social', 'video'),
('c32', 'Pedir una degustacion', 'En una panaderia, fiambreria o similar, pedi probar antes de comprar', 'medio', 8, 'social', 'video'),
('c33', 'Aplaudir solo en publico', 'Aplaudi solo en un lugar publico como si hubieras visto algo increible', 'medio', 8, 'performance', 'video'),
('c34', 'Sentarte en la mesa de un desconocido', 'En un food court o plaza de comidas, pedi sentarte en la mesa de alguien que no conoces', 'medio', 8, 'social', 'foto'),
('c35', 'Pedir un autografo a un random', 'Pedile un autografo a alguien random como si fuera famoso', 'medio', 8, 'social', 'foto'),
('c36', 'Cantar el feliz cumpleanios a un desconocido', 'Cantale el feliz cumpleanios a alguien que no conoces en un lugar publico', 'dificil', 12, 'performance', 'video'),
('c37', 'Hacer una devolucion inventada', 'Intenta devolver un producto que claramente no compraste ahi', 'dificil', 12, 'social', 'video'),
('c38', 'Pedir un descuento por ser tu cumpleanios', 'En cualquier comercio, deci que es tu cumpleanios y pedi descuento', 'dificil', 12, 'social', 'video'),
('c39', 'Hablarle al mozo en otro idioma', 'Pedi algo en un restaurante hablando en un idioma inventado o real que no sea espaniol', 'dificil', 12, 'performance', 'video'),
('c40', 'Hacer una queja inventada', 'Quejate de algo absurdo en un local (ej: la musica esta muy baja)', 'dificil', 12, 'social', 'video'),
('c41', 'Pedir wifi a un vecino', 'Tocale el timbre a un vecino y pedile la contrasenha del wifi', 'dificil', 12, 'social', 'video'),
('c42', 'Gritar lo logre en publico', 'En un lugar publico, grita LO LOGRE con los brazos arriba', 'dificil', 12, 'performance', 'video'),
('c43', 'Intentar pagar con un billete de juguete', 'Saca un billete falso/de juguete e intenta pagar con eso (aclarando despues que es joda)', 'dificil', 12, 'social', 'video'),
('c44', 'Selfie con un guardia de seguridad', 'Pedile una selfie a un guardia de seguridad', 'dificil', 12, 'social', 'foto'),
('c45', 'Foto haciendo yoga en publico', 'Hace una pose de yoga en un lugar publico concurrido', 'dificil', 12, 'performance', 'foto'),
('c46', 'Dar un discurso en publico', 'Para en un lugar publico y da un discurso de al menos 15 segundos sobre cualquier tema', 'extremo', 15, 'performance', 'video'),
('c47', 'Pedir matrimonio falso', 'Arrodillate frente a un desconocido y simula una propuesta de matrimonio', 'extremo', 15, 'performance', 'video'),
('c48', 'Hacer un brindis con desconocidos', 'En un bar, levanta tu vaso y propone un brindis a la mesa de al lado', 'extremo', 15, 'social', 'video'),
('c49', 'Contar un chiste a desconocidos', 'Acercate a un grupo de desconocidos y contales un chiste', 'extremo', 15, 'social', 'video'),
('c50', 'Hacer de estatua viviente', 'Quedarte inmovil como estatua viviente en un lugar publico por al menos 30 segundos', 'extremo', 15, 'performance', 'video');
